#!/bin/bash

cd ~/ArchConfig

# show differences from last commit
# differences=$(git diff $(git log | grep commit | head -n 2 | tail -n 1 | sed -e "s/commit //g") | grep -E '^diff|\/dev\/null' | sed "s/diff.* b\///")

# differences=$(git diff b17b 6d4a | grep -E '^diff|\/dev\/null' | sed -e "s/diff.* b\///" -e "s/^\+.*/deleted/g" -e "s/^\-.*/added/g")
differences=($(git diff b17b 6d4a | grep -E '^diff|\/dev\/null' | sed -e "s/^diff.* b\///" -e "s/^\+.*/deleted/g" -e "s/^\-.*/added/g"))

# differences is an array containing files and words
# echo ${#differences[@]} -> 28

for item in ${differences[@]}
do
    echo $item
done

# figure out:
    # added files (add them to local if not in local)
    # deleted files
    # differing files (ask if want to update)
    # same but directories ^

# if ---/dev/null, file was created
# if +++/dev/null, file was deleted

# get "diff" line
# get --- line
# get +++ line

